// <auto-generated />
using System;
using EMPLOYEE_MANAGEMENT.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMPLOYEE_MANAGEMENT.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118110248_InitialDbSetup")]
    partial class InitialDbSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMPLOYEE_MANAGEMENT.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            Description = "Handles employee relations and recruitment.",
                            Name = "Human Resources",
                            UpdatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            Description = "Responsible for technical systems and support.",
                            Name = "IT Department",
                            UpdatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622)
                        });
                });

            modelBuilder.Entity("EMPLOYEE_MANAGEMENT.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AadharNumber = "123456789012",
                            CreatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            DepartmentId = 1,
                            Name = "John Doe",
                            PhoneNumber = "9876543210",
                            RoleId = 1,
                            UpdatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AadharNumber = "987654321098",
                            CreatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            DepartmentId = 2,
                            Name = "Jane Smith",
                            PhoneNumber = "8765432109",
                            RoleId = 2,
                            UpdatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("EMPLOYEE_MANAGEMENT.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            Description = "Administrator role",
                            Name = "Admin",
                            UpdatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            Description = "Employee role",
                            Name = "Employee",
                            UpdatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            Description = "Manages HR operations",
                            Name = "HR Manager",
                            UpdatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622),
                            Description = "Responsible for development",
                            Name = "Software Engineer",
                            UpdatedDate = new DateTime(2025, 11, 18, 11, 2, 47, 656, DateTimeKind.Utc).AddTicks(6622)
                        });
                });

            modelBuilder.Entity("EMPLOYEE_MANAGEMENT.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword123",
                            Username = "john.doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            IsActive = true,
                            PasswordHash = "hashedpassword456",
                            Username = "jane.smith"
                        });
                });

            modelBuilder.Entity("EMPLOYEE_MANAGEMENT.Domain.Entities.Employee", b =>
                {
                    b.HasOne("EMPLOYEE_MANAGEMENT.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMPLOYEE_MANAGEMENT.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMPLOYEE_MANAGEMENT.Domain.Entities.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("EMPLOYEE_MANAGEMENT.Domain.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EMPLOYEE_MANAGEMENT.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EMPLOYEE_MANAGEMENT.Domain.Entities.User", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
